### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by keyu-ys** [sensorsdata/sa-sdk-node#5]
![image](https://user-images.githubusercontent.com/11641356/89971331-88181300-dc8d-11ea-864d-d434d016f4df.png)

**Comment by weiyi0** [comment]
[新版本](https://github.com/sensorsdata/sa-sdk-node/releases/tag/v1.2.2)已经做了修复，感谢您的反馈
