### ISSUE TITLE
sensorsdata / sa-sdk-node Release v1.2.2 升级问题

### ISSUE THREAD

**Issue by MickeyMouse-lh** [sensorsdata/sa-sdk-node#6]
![4741597204307_ pic_hd](https://user-images.githubusercontent.com/29797274/89974719-6bcca400-dc96-11ea-8fd4-72f4a31725e9.jpg)
我本地安装最新包，报错如上图。
Release v1.2.2
@mrcannot mrcannot released this 32 minutes ago

修复：
修复 bug ReferenceError: regeneratorRuntime is not defined #5

**Comment by weiyi0** [comment]
> ![4741597204307_ pic_hd](https://user-images.githubusercontent.com/29797274/89974719-6bcca400-dc96-11ea-8fd4-72f4a31725e9.jpg)
> 我本地安装最新包，报错如上图。
> Release v1.2.2
> @mrcannot mrcannot released this 32 minutes ago
> 
> 修复：
> 修复 bug ReferenceError: regeneratorRuntime is not defined #5

应该是您这边本地的 node 缓存还存在，您可以看一下 node_modules 里面 SDK 的版本是多少

**Comment by MickeyMouse-lh** [comment]
最新，1.2.2

weiyi <notifications@github.com> 于2020年8月12日周三 下午12:30写道：

**Comment by weiyi0** [comment]
1.2.1 版本的 SDK 确实会出现这个问题，我这边使用 1.2.2 版本的 SDK 已经无法复现了，方便的话我们远程看一下吧
